resources:
  - name: test-fetch
    type: git
    source:
      uri: https://github.com/phkunt/Concourse_test.git
 
jobs:
  - name: job-execute_HelloWorld
    public: true
    plan:
    - get: test-fetch
    - task: execute_script
      config:
           platform: linux
           image_resource:
             type: docker-image
             source: {repository: busybox}
 
           inputs:
             - name: test-fetch
 
           run:
             path: test-fetch/HelloWorld.sh
             args: ["((text))"]
